# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoprocess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 100, 471, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video_label = QtWidgets.QLabel(self.frame)
        self.video_label.setGeometry(QtCore.QRect(0, 50, 251, 151))
        self.video_label.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 30, 121, 20))
        self.label.setObjectName("label")
        self.result_label = QtWidgets.QLabel(self.frame)
        self.result_label.setGeometry(QtCore.QRect(310, 50, 141, 151))
        self.result_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(350, 30, 121, 20))
        self.label_2.setObjectName("label_2")
        self.slider = QtWidgets.QSlider(self.frame)
        self.slider.setGeometry(QtCore.QRect(40, 210, 160, 16))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.video_path = QtWidgets.QLabel(self.frame)
        self.video_path.setGeometry(QtCore.QRect(0, 230, 241, 20))
        self.video_path.setText("")
        self.video_path.setObjectName("video_path")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(90, 350, 621, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_open = QtWidgets.QPushButton(self.frame_2)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.btn_start = QtWidgets.QPushButton(self.frame_2)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_play = QtWidgets.QPushButton(self.frame_2)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_stop = QtWidgets.QPushButton(self.frame_2)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.btn_exit = QtWidgets.QPushButton(self.frame_2)
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "视频显示"))
        self.label_2.setText(_translate("MainWindow", "检测结果"))
        self.btn_open.setText(_translate("MainWindow", "选择视频"))
        self.btn_start.setText(_translate("MainWindow", "开始检测"))
        self.btn_play.setText(_translate("MainWindow", "播放"))
        self.btn_stop.setText(_translate("MainWindow", "暂停"))
        self.btn_exit.setText(_translate("MainWindow", "退出"))
